name: Development

on: [push, pull_request]

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - "3.0"
          - "3.1"
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: truffleruby-head
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Install liburing
      if: ${{ matrix.ruby == '3.1' && matrix.os == 'ubuntu' }}
      run: |
        git clone https://github.com/axboe/liburing.git
        cd liburing
        ./configure
        make
        sudo make install
    
    - name: Build extensions
      timeout-minutes: 5
      run: ${{matrix.env}} bundle exec bake build
    
    - name: Run tests
      timeout-minutes: 5
      run: ${{matrix.env}} bundle exec sus-parallel
